### ISSUE TITLE
Infected

### ISSUE THREAD

**Issue by Exception0170** [zxo2004/DarkComet-RAT-5.3.1#2]
Can you upload a non-infected file?

**Comment by ssjblue-xxx** [comment]
he can't...

**Comment by ege75753** [comment]
use Quasar rat from github its safe but my personality didnt let me run in my main host so im running Quasasr Server in a VM

**Comment by monkeyrizz** [comment]
> use Quasar rat from github its safe but my personality didnt let me run in my main host so im running Quasasr Server in a VM

do you know how to install quasar rat?
